version: '3.7'
services:
  monorepo:
    container_name: monorepo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true